spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/grab_clone
    username: grab_user
    password: grab_password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER:}
    password: ${MAILTRAP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    show-sql: true